export default {
  Introduction: [
    "Introduction#",
    "Welcome to the world of Illuvium. A shattered land of beauty and wonder. Travel the vast and varied landscape hunting dangerous beasts, then capture them to battle in the Arenas or trade via the exchange.",
    "Prior to launch of the game, $ILV holders may choose to stake $ILV to access the liquidity mining program (a type of ‘yield farming’ that has become popular with DeFi protocols where the founding teams seek to decentralise the governance of the protocol).",
    "The purpose of the liquidity mining program is to distribute $ILV from the Illuvium Treasury to early Illuvium community members to: 1) achieve a distributed holding of $ILV tokens across more of the Illuvium community, 2) incentivise new people to participate in the Illuvium community, and 3) to enable a more liquid and transparent market for the trading of $ILV. The greater the size of the Illuvium community, the greater the prospects of decentralised governance as well as a self-regulating community that discourages bad actors and manipulation of governance and the game. Once the game is launched, users can stake $ILV as a signal of belief and support in the game and its governance model and receive access to governance and distributions from in-game fees.",
    "A fully decentralized protocol, Illuvium represents a new age in gaming. It has been engineered from the ground-up to support the long-term sustainability of the Illuvium game and governance and provide players with a AAA-rated blockchain gaming experience. What makes Illuvium unique is that stakers receive regular distributions and can vote on everything from tokenomics related issues to the features in the game itself. With Illuvium, the power to define the project into the future is purposefully left to those who stake in the protocol.",
  ],

  "Why DeFi?": [
    "Why DeFi?#",
    "The primary goal of the project is to create a fully decentralised game that can run autonomously. Over the last 18 months, and particularly in the last six, DeFi apps have seen impressive growth and rapid development. There are hundreds of DeFi projects gaining traction today—from trading, lending, and wallet interfaces, to assets and communities representing over 15B $USD in value. DeFi allows us to leverage this exciting growth to bootstrap a solvent platform that can hit the ground running for the increasing market interest in DeFi projects.",
    "We are already starting to see a shift away from “novelty projects” that don’t add tangible value because ultimately they are unsustainable. We strongly believe a decentralised gaming economy provides the best fusion between crypto/blockchain/DAO enthusiasts and gamers looking for open access devoid of corporate interference.",
    "There are currently no AAA gaming titles with cinematic quality 3D special effects in an immersive open-world RPG built in DeFi, and Illuvium merges gaming and cryptocurrency in a unique synergy that holds allure for crypto enthusiasts, dedicated gamers, and the curious tech-savvy public. By having gorgeous, functional, and rare NFTs, as well as a high replay value, Illuvium will keep players interested in the $ILV protocol longer, ensuring the stability of the underlying NFT assets and the token pool.",
    "We are already starting to see a shift away from “novelty projects” that don’t add tangible value because ultimately they are unsustainable. We strongly believe a decentralised gaming economy provides the best fusion between crypto/blockchain/DAO enthusiasts and gamers looking for open access devoid of corporate interference.",
    "\n" +
      "There are currently no AAA gaming titles with cinematic quality 3D special effects in an immersive open-world RPG built in DeFi, and Illuvium merges gaming and cryptocurrency in a unique synergy that holds allure for crypto enthusiasts, dedicated gamers, and the curious tech-savvy public. By having gorgeous, functional, and rare NFTs, as well as a high replay value, Illuvium will keep players interested in the $ILV protocol longer, ensuring the stability of the underlying NFT assets and the token pool.",
    "We are already starting to see a shift away from “novelty projects” that don’t add tangible value because ultimately they are unsustainable. We strongly believe a decentralised gaming economy provides the best fusion between crypto/blockchain/DAO enthusiasts and gamers looking for open access devoid of corporate interference.",
    "There are currently no AAA gaming titles with cinematic quality 3D special effects in an immersive open-world RPG built in DeFi, and Illuvium merges gaming and cryptocurrency in a unique synergy that holds allure for crypto enthusiasts, dedicated gamers, and the curious tech-savvy public. By having gorgeous, functional, and rare NFTs, as well as a high replay value, Illuvium will keep players interested in the $ILV protocol longer, ensuring the stability of the underlying NFT assets and the token pool.\n",
  ],
  "Layer 2 Ethereum Scaling Solution - Immutable X": [],
};
